services:
  nestjs-api-node-prod:
    container_name: nestjs-api-node-prod    
    build:
      context: .
      target: production-distroless    
      dockerfile: Dockerfile.prod  
    volumes:
      - .:/app
      - /app/node_modules      
    ports:
      - 3005:3000
    depends_on:
      - mongo-node  
      
  nestjs-api-node-prod-alpine:
    container_name: nestjs-api-node-prod-alpine    
    build:
      context: .
      target: production-alpine    
      dockerfile: Dockerfile.prod  
    volumes:
      - .:/app
      - /app/node_modules      
    ports:
      - 3004:3000
    depends_on:
      - mongo-node  
      
  nestjs-api-node-dev:
    container_name: nestjs-api-node-dev    
    build:
      context: .
      target: dev-distroless    
      dockerfile: Dockerfile.prod  
    volumes:
      - .:/app
      - /app/node_modules      
    ports:
      - 3003:3000
      
  nestjs-api-node-local:
    container_name: nestjs-api-node-local    
    build:
      context: .
      target: local    
      dockerfile: Dockerfile.prod  
    volumes:
      - .:/app
      - /app/node_modules      
    ports:
      - 3002:3000
    depends_on:
      - mongo-node  

  mongo-node:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  node_modules: