services:
  nestjs-api:
    container_name: nestjs-api
    restart: unless-stopped
    command: npm run start:dev
    build: .      
    volumes:
      - .:/app
      - node_modules:/app/node_modules      
    ports:
      - 3000:3000
    depends_on:
      - mongo  

  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example      

volumes:
  node_modules: